services:
  app:
    build:
      target: prod
    environment:
      APP_ENV: prod
      APP_DEBUG: '0'
    volumes:
      - .:/var/www/html
      - ./docker/Caddyfile.prod:/etc/frankenphp/Caddyfile
      - ./docker/php/conf.d/app.ini:/usr/local/etc/php/conf.d/app.ini
